services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - ./backend/data:/app/data
      - ./backend/documents:/app/documents
      - ./backend/models:/app/models_data
    environment:
      - DATABASE_URL=sqlite:////app/data/versicherungsmanager.db
      - SECRET_KEY=changeme123
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    network_mode: "host"
    restart: always
    depends_on:
      - backend
