# Copyright (c) 2026 Dennis Guse. All rights reserved.
# Licensed under the MIT License. See LICENSE file in project root.

"""Complete removal of a user's data (right to erasure)."""

import os
import shutil

from sqlalchemy import or_
from sqlalchemy.orm import Session

import models

DOCUMENTS_DIR = os.path.abspath("documents")
INBOX_BASE_DIR = os.path.join(DOCUMENTS_DIR, "inbox")


def _unlink_document_file(filename: str) -> None:
    # Stored names are generated by the app; the basename check is a guard against a
    # tampered row ever pointing outside the documents folder.
    if not filename or os.path.basename(filename) != filename:
        return
    try:
        os.remove(os.path.join(DOCUMENTS_DIR, filename))
    except FileNotFoundError:
        pass
    except OSError as e:
        print(f"[Delete User] could not remove file: {type(e).__name__}")


def delete_user_completely(db: Session, user: models.User) -> None:
    """Deletes the account with its insurances, claims, premium history and every
    document - both the database rows and the files on disk (permanent documents
    and the personal inbox folder), which a plain row delete would leave behind."""
    insurances = db.query(models.Insurance).filter(models.Insurance.owner_id == user.id).all()
    insurance_ids = [ins.id for ins in insurances]

    conditions = [models.Document.owner_id == user.id]
    if insurance_ids:
        conditions.append(models.Document.insurance_id.in_(insurance_ids))
    documents = db.query(models.Document).filter(or_(*conditions)).all()
    filenames = [doc.filename for doc in documents]

    for doc in documents:
        db.delete(doc)
    for ins in insurances:
        db.delete(ins)
    inbox_dir = os.path.join(INBOX_BASE_DIR, str(user.id))
    db.delete(user)
    db.commit()

    # Files go only after the database change has succeeded, so a failure can never
    # leave rows that point to files that are already gone.
    for filename in filenames:
        _unlink_document_file(filename)
    if os.path.isdir(inbox_dir) and os.path.dirname(os.path.abspath(inbox_dir)) == INBOX_BASE_DIR:
        shutil.rmtree(inbox_dir, ignore_errors=True)
